# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mini_app_Qt_VTK.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1116, 821)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 1111, 761))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(190, 190))
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(20, 730, 131, 30))
        self.radioButton.setObjectName("radioButton")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(20, 690, 95, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 201, 491))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(10, 80, 181, 121))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.layoutWidget = QtWidgets.QWidget(self.frame_4)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 40, 161, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lightPos_x = QtWidgets.QSlider(self.layoutWidget)
        self.lightPos_x.setMinimum(-300)
        self.lightPos_x.setMaximum(400)
        self.lightPos_x.setSingleStep(5)
        self.lightPos_x.setPageStep(100)
        self.lightPos_x.setOrientation(QtCore.Qt.Horizontal)
        self.lightPos_x.setObjectName("lightPos_x")
        self.verticalLayout.addWidget(self.lightPos_x)
        self.lightPos_y = QtWidgets.QSlider(self.layoutWidget)
        self.lightPos_y.setMinimum(-300)
        self.lightPos_y.setMaximum(500)
        self.lightPos_y.setSingleStep(5)
        self.lightPos_y.setPageStep(100)
        self.lightPos_y.setOrientation(QtCore.Qt.Horizontal)
        self.lightPos_y.setObjectName("lightPos_y")
        self.verticalLayout.addWidget(self.lightPos_y)
        self.lightPos_z = QtWidgets.QSlider(self.layoutWidget)
        self.lightPos_z.setMinimum(-100)
        self.lightPos_z.setMaximum(400)
        self.lightPos_z.setSingleStep(5)
        self.lightPos_z.setPageStep(100)
        self.lightPos_z.setOrientation(QtCore.Qt.Horizontal)
        self.lightPos_z.setObjectName("lightPos_z")
        self.verticalLayout.addWidget(self.lightPos_z)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 210, 181, 51))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lightIntensity = QtWidgets.QSlider(self.frame_3)
        self.lightIntensity.setGeometry(QtCore.QRect(10, 30, 160, 16))
        self.lightIntensity.setMaximum(200)
        self.lightIntensity.setSingleStep(1)
        self.lightIntensity.setOrientation(QtCore.Qt.Horizontal)
        self.lightIntensity.setObjectName("lightIntensity")
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setGeometry(QtCore.QRect(10, 270, 181, 51))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.light_coneAngle = QtWidgets.QSlider(self.frame_5)
        self.light_coneAngle.setGeometry(QtCore.QRect(10, 30, 160, 16))
        self.light_coneAngle.setMaximum(91)
        self.light_coneAngle.setSingleStep(1)
        self.light_coneAngle.setProperty("value", 40)
        self.light_coneAngle.setOrientation(QtCore.Qt.Horizontal)
        self.light_coneAngle.setObjectName("light_coneAngle")
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setGeometry(QtCore.QRect(10, 330, 181, 101))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_5 = QtWidgets.QLabel(self.frame_6)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.light_focalPoint = QtWidgets.QRadioButton(self.frame_6)
        self.light_focalPoint.setGeometry(QtCore.QRect(10, 60, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.light_focalPoint.setFont(font)
        self.light_focalPoint.setObjectName("light_focalPoint")
        self.light_focalPoint_button = QtWidgets.QPushButton(self.frame_6)
        self.light_focalPoint_button.setGeometry(QtCore.QRect(10, 30, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.light_focalPoint_button.setFont(font)
        self.light_focalPoint_button.setObjectName("light_focalPoint_button")
        self.saveButton = QtWidgets.QPushButton(self.frame_2)
        self.saveButton.setGeometry(QtCore.QRect(40, 40, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.saveButton.setFont(font)
        self.saveButton.setDefault(False)
        self.saveButton.setFlat(False)
        self.saveButton.setObjectName("saveButton")
        self.frame_9 = QtWidgets.QFrame(self.frame_2)
        self.frame_9.setGeometry(QtCore.QRect(10, 430, 181, 51))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.rb_PreviewShadows = QtWidgets.QRadioButton(self.frame_9)
        self.rb_PreviewShadows.setGeometry(QtCore.QRect(10, 20, 101, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.rb_PreviewShadows.setFont(font)
        self.rb_PreviewShadows.setObjectName("rb_PreviewShadows")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(10, 510, 201, 171))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_6 = QtWidgets.QLabel(self.frame_7)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.frame_8 = QtWidgets.QFrame(self.frame_7)
        self.frame_8.setGeometry(QtCore.QRect(10, 40, 181, 121))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.label_7 = QtWidgets.QLabel(self.frame_8)
        self.label_7.setGeometry(QtCore.QRect(10, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.layoutWidget_2 = QtWidgets.QWidget(self.frame_8)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 40, 161, 81))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cameraPos_x = QtWidgets.QSlider(self.layoutWidget_2)
        self.cameraPos_x.setMinimum(-300)
        self.cameraPos_x.setMaximum(400)
        self.cameraPos_x.setSingleStep(5)
        self.cameraPos_x.setPageStep(100)
        self.cameraPos_x.setOrientation(QtCore.Qt.Horizontal)
        self.cameraPos_x.setObjectName("cameraPos_x")
        self.verticalLayout_2.addWidget(self.cameraPos_x)
        self.cameraPos_y = QtWidgets.QSlider(self.layoutWidget_2)
        self.cameraPos_y.setMinimum(-300)
        self.cameraPos_y.setMaximum(500)
        self.cameraPos_y.setSingleStep(5)
        self.cameraPos_y.setPageStep(100)
        self.cameraPos_y.setOrientation(QtCore.Qt.Horizontal)
        self.cameraPos_y.setObjectName("cameraPos_y")
        self.verticalLayout_2.addWidget(self.cameraPos_y)
        self.cameraPos_z = QtWidgets.QSlider(self.layoutWidget_2)
        self.cameraPos_z.setMinimum(-100)
        self.cameraPos_z.setMaximum(400)
        self.cameraPos_z.setSingleStep(5)
        self.cameraPos_z.setPageStep(100)
        self.cameraPos_z.setOrientation(QtCore.Qt.Horizontal)
        self.cameraPos_z.setObjectName("cameraPos_z")
        self.verticalLayout_2.addWidget(self.cameraPos_z)
        self.vtk_panel = QtWidgets.QFrame(self.splitter)
        self.vtk_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vtk_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vtk_panel.setObjectName("vtk_panel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1116, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Points"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Wireframe"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Surface"))
        self.label.setText(_translate("MainWindow", "Light Configuration"))
        self.label_3.setText(_translate("MainWindow", "Position (x, y, z)"))
        self.label_2.setText(_translate("MainWindow", "Intensity"))
        self.label_4.setText(_translate("MainWindow", "Cone Angle"))
        self.label_5.setText(_translate("MainWindow", "Focal point (Default : 0,0,0)"))
        self.light_focalPoint.setText(_translate("MainWindow", "Follow target"))
        self.light_focalPoint_button.setText(_translate("MainWindow", "Set on target"))
        self.saveButton.setText(_translate("MainWindow", "Change Source"))
        self.label_8.setText(_translate("MainWindow", "Shadows"))
        self.rb_PreviewShadows.setText(_translate("MainWindow", "Preview"))
        self.label_6.setText(_translate("MainWindow", "Camera Configuration"))
        self.label_7.setText(_translate("MainWindow", "Position (x, y, z)"))

