# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mini_app_Qt_VTK.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1047, 816)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setMinimumSize(QtCore.QSize(190, 190))
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.frame_3)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.label_8 = QtWidgets.QLabel(self.splitter_2)
        self.label_8.setObjectName("label_8")
        self.width = QtWidgets.QSpinBox(self.splitter_2)
        self.width.setMinimum(1)
        self.width.setMaximum(4096)
        self.width.setProperty("value", 256)
        self.width.setObjectName("width")
        self.gridLayout.addWidget(self.splitter_2, 0, 0, 1, 1)
        self.splitter_3 = QtWidgets.QSplitter(self.frame_3)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.label_9 = QtWidgets.QLabel(self.splitter_3)
        self.label_9.setObjectName("label_9")
        self.height = QtWidgets.QSpinBox(self.splitter_3)
        self.height.setMinimum(1)
        self.height.setMaximum(4096)
        self.height.setProperty("value", 128)
        self.height.setObjectName("height")
        self.gridLayout.addWidget(self.splitter_3, 1, 0, 1, 1)
        self.button_RTX = QtWidgets.QPushButton(self.frame_3)
        self.button_RTX.setObjectName("button_RTX")
        self.gridLayout.addWidget(self.button_RTX, 2, 0, 1, 2)
        self.gridLayout_2.addWidget(self.frame_3, 4, 0, 1, 1)
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout_2.addWidget(self.radioButton, 3, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 2, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setMaximumSize(QtCore.QSize(1000, 100000))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.saveButton = QtWidgets.QPushButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.saveButton.setFont(font)
        self.saveButton.setDefault(False)
        self.saveButton.setFlat(False)
        self.saveButton.setObjectName("saveButton")
        self.verticalLayout_4.addWidget(self.saveButton)
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.lightIntensity = QtWidgets.QSlider(self.tab_3)
        self.lightIntensity.setMaximum(200)
        self.lightIntensity.setSingleStep(1)
        self.lightIntensity.setOrientation(QtCore.Qt.Horizontal)
        self.lightIntensity.setObjectName("lightIntensity")
        self.verticalLayout_4.addWidget(self.lightIntensity)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.lightPos_x = QtWidgets.QSlider(self.tab_3)
        self.lightPos_x.setMinimum(-300)
        self.lightPos_x.setMaximum(400)
        self.lightPos_x.setSingleStep(5)
        self.lightPos_x.setPageStep(100)
        self.lightPos_x.setOrientation(QtCore.Qt.Horizontal)
        self.lightPos_x.setObjectName("lightPos_x")
        self.verticalLayout.addWidget(self.lightPos_x)
        self.lightPos_y = QtWidgets.QSlider(self.tab_3)
        self.lightPos_y.setMinimum(-300)
        self.lightPos_y.setMaximum(500)
        self.lightPos_y.setSingleStep(5)
        self.lightPos_y.setPageStep(100)
        self.lightPos_y.setOrientation(QtCore.Qt.Horizontal)
        self.lightPos_y.setObjectName("lightPos_y")
        self.verticalLayout.addWidget(self.lightPos_y)
        self.lightPos_z = QtWidgets.QSlider(self.tab_3)
        self.lightPos_z.setMinimum(-100)
        self.lightPos_z.setMaximum(400)
        self.lightPos_z.setSingleStep(5)
        self.lightPos_z.setPageStep(100)
        self.lightPos_z.setOrientation(QtCore.Qt.Horizontal)
        self.lightPos_z.setObjectName("lightPos_z")
        self.verticalLayout.addWidget(self.lightPos_z)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.light_coneAngle = QtWidgets.QSlider(self.tab_3)
        self.light_coneAngle.setMaximum(91)
        self.light_coneAngle.setSingleStep(1)
        self.light_coneAngle.setProperty("value", 40)
        self.light_coneAngle.setOrientation(QtCore.Qt.Horizontal)
        self.light_coneAngle.setObjectName("light_coneAngle")
        self.verticalLayout_4.addWidget(self.light_coneAngle)
        self.frame_2 = QtWidgets.QFrame(self.tab_3)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.light_focalPoint_button = QtWidgets.QPushButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.light_focalPoint_button.setFont(font)
        self.light_focalPoint_button.setObjectName("light_focalPoint_button")
        self.horizontalLayout.addWidget(self.light_focalPoint_button)
        self.light_focalPoint = QtWidgets.QRadioButton(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.light_focalPoint.setFont(font)
        self.light_focalPoint.setObjectName("light_focalPoint")
        self.horizontalLayout.addWidget(self.light_focalPoint)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.rb_PreviewShadows = QtWidgets.QRadioButton(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.rb_PreviewShadows.setFont(font)
        self.rb_PreviewShadows.setObjectName("rb_PreviewShadows")
        self.verticalLayout_4.addWidget(self.rb_PreviewShadows)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_7 = QtWidgets.QLabel(self.tab_4)
        self.label_7.setMaximumSize(QtCore.QSize(300, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.cameraPos_x = QtWidgets.QSlider(self.tab_4)
        self.cameraPos_x.setMinimum(-300)
        self.cameraPos_x.setMaximum(400)
        self.cameraPos_x.setSingleStep(5)
        self.cameraPos_x.setPageStep(100)
        self.cameraPos_x.setOrientation(QtCore.Qt.Horizontal)
        self.cameraPos_x.setObjectName("cameraPos_x")
        self.verticalLayout_2.addWidget(self.cameraPos_x)
        self.cameraPos_y = QtWidgets.QSlider(self.tab_4)
        self.cameraPos_y.setMinimum(-300)
        self.cameraPos_y.setMaximum(500)
        self.cameraPos_y.setSingleStep(5)
        self.cameraPos_y.setPageStep(100)
        self.cameraPos_y.setOrientation(QtCore.Qt.Horizontal)
        self.cameraPos_y.setObjectName("cameraPos_y")
        self.verticalLayout_2.addWidget(self.cameraPos_y)
        self.cameraPos_z = QtWidgets.QSlider(self.tab_4)
        self.cameraPos_z.setMinimum(-100)
        self.cameraPos_z.setMaximum(400)
        self.cameraPos_z.setSingleStep(5)
        self.cameraPos_z.setPageStep(100)
        self.cameraPos_z.setOrientation(QtCore.Qt.Horizontal)
        self.cameraPos_z.setObjectName("cameraPos_z")
        self.verticalLayout_2.addWidget(self.cameraPos_z)
        self.verticalLayout_6.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_2.addWidget(self.tabWidget, 6, 0, 1, 1)
        self.vtk_panel = QtWidgets.QFrame(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vtk_panel.sizePolicy().hasHeightForWidth())
        self.vtk_panel.setSizePolicy(sizePolicy)
        self.vtk_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vtk_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vtk_panel.setObjectName("vtk_panel")
        self.verticalLayout_5.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1047, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_8.setText(_translate("MainWindow", "Width  :"))
        self.label_9.setText(_translate("MainWindow", "Height :"))
        self.button_RTX.setText(_translate("MainWindow", "Compute RT"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Points"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Wireframe"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Surface"))
        self.label.setText(_translate("MainWindow", "Light Configuration"))
        self.saveButton.setText(_translate("MainWindow", "Change Source"))
        self.label_2.setText(_translate("MainWindow", "Intensity"))
        self.label_3.setText(_translate("MainWindow", "Position (x, y, z)"))
        self.label_4.setText(_translate("MainWindow", "Cone Angle"))
        self.label_5.setText(_translate("MainWindow", "Focal point (Default : 0,0,0)"))
        self.light_focalPoint_button.setText(_translate("MainWindow", "Set on target"))
        self.light_focalPoint.setText(_translate("MainWindow", "Follow target"))
        self.rb_PreviewShadows.setText(_translate("MainWindow", "Preview Shadows"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Light"))
        self.label_6.setText(_translate("MainWindow", "Camera Configuration"))
        self.label_7.setText(_translate("MainWindow", "Position (x, y, z)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Camera"))

