# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mini_app_Qt_VTK.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 801, 561))
        self.splitter.setMinimumSize(QtCore.QSize(190, 190))
        self.splitter.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.frame = QtWidgets.QFrame(self.splitter)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(10, 50, 131, 30))
        self.radioButton.setObjectName("radioButton")
        self.comboBox = QtWidgets.QComboBox(self.frame)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 95, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.Resolution = QtWidgets.QSlider(self.frame)
        self.Resolution.setGeometry(QtCore.QRect(10, 90, 141, 16))
        self.Resolution.setOrientation(QtCore.Qt.Horizontal)
        self.Resolution.setObjectName("Resolution")
        self.saveButton = QtWidgets.QPushButton(self.frame)
        self.saveButton.setGeometry(QtCore.QRect(10, 150, 75, 23))
        self.saveButton.setObjectName("saveButton")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(10, 200, 201, 231))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(10, 40, 181, 111))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.widget = QtWidgets.QWidget(self.frame_4)
        self.widget.setGeometry(QtCore.QRect(10, 40, 161, 61))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lightPos_x = QtWidgets.QSlider(self.widget)
        self.lightPos_x.setMaximum(999)
        self.lightPos_x.setSingleStep(5)
        self.lightPos_x.setPageStep(100)
        self.lightPos_x.setOrientation(QtCore.Qt.Horizontal)
        self.lightPos_x.setObjectName("lightPos_x")
        self.verticalLayout.addWidget(self.lightPos_x)
        self.lightPos_y = QtWidgets.QSlider(self.widget)
        self.lightPos_y.setMaximum(999)
        self.lightPos_y.setSingleStep(5)
        self.lightPos_y.setPageStep(100)
        self.lightPos_y.setOrientation(QtCore.Qt.Horizontal)
        self.lightPos_y.setObjectName("lightPos_y")
        self.verticalLayout.addWidget(self.lightPos_y)
        self.lightPos_z = QtWidgets.QSlider(self.widget)
        self.lightPos_z.setMaximum(999)
        self.lightPos_z.setSingleStep(5)
        self.lightPos_z.setPageStep(100)
        self.lightPos_z.setOrientation(QtCore.Qt.Horizontal)
        self.lightPos_z.setObjectName("lightPos_z")
        self.verticalLayout.addWidget(self.lightPos_z)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(10, 160, 181, 51))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lightIntensity = QtWidgets.QSlider(self.frame_3)
        self.lightIntensity.setGeometry(QtCore.QRect(10, 30, 160, 16))
        self.lightIntensity.setMaximum(200)
        self.lightIntensity.setSingleStep(1)
        self.lightIntensity.setOrientation(QtCore.Qt.Horizontal)
        self.lightIntensity.setObjectName("lightIntensity")
        self.vtk_panel = QtWidgets.QFrame(self.splitter)
        self.vtk_panel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vtk_panel.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vtk_panel.setObjectName("vtk_panel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton.setText(_translate("MainWindow", "RadioButton"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Points"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Wireframe"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Surface"))
        self.saveButton.setText(_translate("MainWindow", "Save"))
        self.label.setText(_translate("MainWindow", "Light Configuration"))
        self.label_3.setText(_translate("MainWindow", "Position (x, y, z)"))
        self.label_2.setText(_translate("MainWindow", "Intensity"))

